### ISSUE TITLE
Feature Request: Autocomple parenthesis

### ISSUE THREAD

**Issue by rukano** [dathinaios/spacemacs-supercollider#3]
I know a lot of modes use it in spacemacs already, I wonder why is not working on sclang mode directly?

**Comment by dathinaios** [comment]
Just solved this! :)

I added these instructions to the readme:

> Q: How do I enable automatic matching for parenthesis etc.?
> A: Add `(add-hook 'sclang-mode-hook 'turn-on-smartparens-mode)` to your `.spacemacs` file.
>

**Comment by rukano** [comment]
PErfect! thanks! I'll make a pull request soon for another matter I just discovered!!
