### ISSUE TITLE
Feature request: YASnippets triggering with TAB

### ISSUE THREAD

**Issue by rukano** [dathinaios/spacemacs-supercollider#4]
Right now yas is active as a minor mode, and snippets can be created and expanded only via menu or code. There is no key (standard is `TAB` usually) to trigger the snippet expansion. Would it be possible to make `TAB` the default expansion key for sclang-mode?

**Comment by dathinaios** [comment]
Yes and completion is not working through spacemacs at the moment. I will have a look at some point...

**Comment by rukano** [comment]
I will look at it too, but I'm not a big emacs expert.. maybe over the weekend :)

**Comment by rukano** [comment]
Found a [discussion](https://github.com/joaotavora/yasnippet/issues/526) at the [yasnippet](https://github.com/joaotavora/yasnippet/) repository, since the hotkeys collide (autocomple/expand snippet)... the other solutions i've seen are too **"global"** and might affect the behaviour of the rest of spacemacs...

**Comment by dathinaios** [comment]
yes, the default key binding for snippets is `M-/`. I have mine remapped to `ctrl-p` that I am used to from `vim`. But ideally we need to integrate the completion system of `spacemacs` with the layer and then there is an option for the snippets to appear on the popup with the other suggestions.

I tried to follow the instructions in the "creating layers" docs but without success for now. I will try again at some point.

**Comment by rukano** [comment]
Cool! thanks for your effort! I would try a little bit more, but I forgot my charger in the office over the weekend... Let's see if the battery last long enough to find a solution :)

**Comment by dathinaios** [comment]
I am going to close this as we should follow the way `spacemacs` is implementing snippets. Individual users can then modify as they please. Same goes for my suggestion with snippets showing in completion pop ups. It is an option that can be set by the user in their `.spacemacs`.

**Comment by rukano** [comment]
Sounds reasonable! Thanks!
