### ISSUE TITLE
Should not compile the full downloaded-quarks folder

### ISSUE THREAD

**Issue by dathinaios** [dathinaios/spacemacs-supercollider#6]
At the moment we are compiling the `downloaded-quarks` folder. This folder contains all the quarks that were downloaded independently of whether they are enabled or not. The right way would be to use the list from the main `sclang_config.yaml` file and find a way to import the entries to our custom one. Maybe using a script or a lisp function in the layer.

**Comment by rukano** [comment]
I like the solution you came up with! Very good! Thanks for your effort!
