### ISSUE TITLE
flet is obsolete 

### ISSUE THREAD

**Issue by KonVas** [dathinaios/spacemacs-supercollider#9]
Nothing to worry about, it just seems that things might have shifted a bit in current versions of Spacemacs.

`flet` seems to be obsolete, so I changed it to` cl-flet`

This probably might be worth of checking for new versions. I changed mine and it seems alright so far.

**Comment by dathinaios** [comment]
Thanks for letting me know. I will change it 👍

EDIT: I will test it for a while myself before submitting.

**Comment by dathinaios** [comment]
changed in commit 09bc3fd54467c6bc040ae7e625ad6acd46d2935d
